//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public Nullable<int> LawyerID { get; set; }
        public Nullable<int> NormalUserID { get; set; }
        public string LawyerConfirm { get; set; }
        public string NormalUserConfirm { get; set; }
    
        public virtual Lawyer Lawyer { get; set; }
        public virtual NormalUser NormalUser { get; set; }
    }
}
