//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NormalUser
    {
        public NormalUser()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public string Name { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
