//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingID { get; set; }
        public Nullable<int> RatingValue { get; set; }
        public Nullable<System.DateTime> RatingTime { get; set; }
        public Nullable<int> LawyerID { get; set; }
    
        public virtual Lawyer Lawyer { get; set; }
    }
}
